-- Analysis of ARPCOMMTX Commission Matrix Table
-- This script examines the table structure and retrieves sample data

-- 1. Get table structure/column information
SELECT COLUMN_NAME, 
       DATA_TYPE, 
       CHARACTER_MAXIMUM_LENGTH,
       NUMERIC_PRECISION,
       NUMERIC_SCALE,
       IS_NULLABLE,
       COLUMN_DEFAULT
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'ARPCOMMTX'
ORDER BY ORDINAL_POSITION;

-- 2. Get sample data to understand the matrix structure
SELECT * FROM ARPCOMMTX
ORDER BY PLAN_NO, DIVISION, SECTION
FETCH FIRST 50 ROWS ONLY;

-- 3. Check unique combinations of key fields
SELECT DISTINCT PLAN_NO, DIVISION, SECTION
FROM ARPCOMMTX
ORDER BY PLAN_NO, DIVISION, SECTION;

-- 4. Analyze SALES and PROFIT percentage ranges
SELECT PLAN_NO,
       DIVISION, 
       SECTION,
       MIN(SALES_LOW) as MIN_SALES_LOW,
       MAX(SALES_HIGH) as MAX_SALES_HIGH,
       MIN(PROFIT_LOW) as MIN_PROFIT_LOW, 
       MAX(PROFIT_HIGH) as MAX_PROFIT_HIGH,
       COUNT(*) as RATE_COUNT
FROM ARPCOMMTX
GROUP BY PLAN_NO, DIVISION, SECTION
ORDER BY PLAN_NO, DIVISION, SECTION;

-- 5. Sample commission rate matrix for one plan/division/section
SELECT PLAN_NO,
       DIVISION,
       SECTION,
       SALES_LOW,
       SALES_HIGH, 
       PROFIT_LOW,
       PROFIT_HIGH,
       COMMISSION_RATE
FROM ARPCOMMTX 
WHERE PLAN_NO = (SELECT MIN(PLAN_NO) FROM ARPCOMMTX)
  AND DIVISION = (SELECT MIN(DIVISION) FROM ARPCOMMTX WHERE PLAN_NO = (SELECT MIN(PLAN_NO) FROM ARPCOMMTX))
  AND SECTION = (SELECT MIN(SECTION) FROM ARPCOMMTX WHERE PLAN_NO = (SELECT MIN(PLAN_NO) FROM ARPCOMMTX))
ORDER BY SALES_LOW, PROFIT_LOW;