SELECT X.*, Y.*
FROM jflanary.xmlOrderX,
XMLTABLE ('$doc/transmission/order'  PASSING xmlOrderX.doc AS "doc"
COLUMNS
order_number char(40) PATH 'OrderHeader/order_info/order_number',
po_number VARCHAR(20) PATH 'OrderHeader/order_info/po_number',
po_number_2 VARCHAR(20) PATH 'OrderHeader/order_info/po_number_2',
job_name VARCHAR(40) PATH 'OrderHeader/order_info/job_name',
unique_id VARCHAR(40) PATH 'OrderHeader/order_info/unique_id',
freight_method VARCHAR(40) PATH 'OrderHeader/order_info/freight_method',
vendor_code VARCHAR(40) PATH 'OrderHeader/order_info/vendor_code',
vendor_name VARCHAR(40) PATH 'OrderHeader/order_info/vendor_name',
placed_date VARCHAR(40)  PATH 'OrderHeader/order_info/placed_date', 
requested_pickup_time VARCHAR(40) PATH 'OrderHeader/order_info/requested_pickup_time',
branch_sell VARCHAR(40) PATH 'OrderHeader/order_info/branch_sell',
branch_ship VARCHAR(40) PATH 'OrderHeader/order_info/branch_ship',
ship_code VARCHAR(40) PATH 'OrderHeader/order_info/ship_code',
ship_subcode VARCHAR(40) PATH 'OrderHeader/order_info/ship_subcode',
special_instructions VARCHAR(40) PATH 'OrderHeader/order_info/special_instructions',
order_notes VARCHAR(40) PATH 'OrderHeader/order_info/order_notes',
charge_or_cash VARCHAR(40) PATH 'OrderHeader/order_info/charge_or_cash',
order_type_code VARCHAR(40) PATH 'OrderHeader/order_info/order_type_code',
order_status_code VARCHAR(40) PATH 'OrderHeader/order_info/order_status_code',
order_status_code_override VARCHAR(40) PATH 'OrderHeader/order_info/order_status_code_override',
amount VARCHAR(40) PATH 'OrderHeader/price_header/amount', 
surcharge_amount VARCHAR(40) PATH 'OrderHeader/price_header/surcharge_amount' ,
freight_charges VARCHAR(40) PATH 'OrderHeader/price_header/extra_charges/freight_charges',  
extra_charge VARCHAR(40) PATH 'OrderHeader/price_header/extra_charges/extra_charge',
taxAmount VARCHAR(40) PATH 'OrderHeader/price_header/tax_info/amount',  
percentage VARCHAR(40) PATH 'OrderHeader/price_header/tax_info/percentage', 
override_price VARCHAR(40) PATH 'OrderHeader/price_header/override_price',   
account_number VARCHAR(40) PATH 'OrderHeader/customer_info/account_number',   
account_name VARCHAR(40) PATH 'OrderHeader/customer_info/account_name',     
contact VARCHAR(40) PATH 'OrderHeader/customer_info/contact',     
city VARCHAR(150) PATH 'OrderHeader/ship_to_info/address/city',   
state VARCHAR(2) PATH 'OrderHeader/ship_to_info/address/state',   
zip VARCHAR(10) PATH 'OrderHeader/ship_to_info/address/zip',   
country VARCHAR(40) PATH 'OrderHeader/ship_to_info/address/country',    
address_line_1 VARCHAR(40) PATH 'OrderHeader/ship_to_info/address/address_line_1',   
address_line_2 VARCHAR(40) PATH 'OrderHeader/ship_to_info/address/address_line_2',
address_line_3 VARCHAR(40) PATH 'OrderHeader/ship_to_info/address/address_line_3', 
ShipContact VARCHAR(40) PATH 'OrderHeader/ship_to_info/contact',  
BillCity VARCHAR(40) PATH 'OrderHeader/billing/bill_to_info/address/city',  
Billstate VARCHAR(40) PATH 'OrderHeader/billing/bill_to_info/address/state',  
Billzip VARCHAR(40) PATH 'OrderHeader/billing/bill_to_info/address/zip',  
Billcountry VARCHAR(40) PATH 'OrderHeader/billing/bill_to_info/address/country',  
Billaddress_line_1 VARCHAR(40) PATH 'OrderHeader/billing/bill_to_info/address/address_line_1',  
Billaddress_line_2 VARCHAR(40) PATH 'OrderHeader/billing/bill_to_info/address/address_line_2',  
Billaddress_line_3 VARCHAR(40) PATH 'OrderHeader/billing/bill_to_info/address/address_line_3',
card_info VARCHAR(40) PATH 'OrderHeader/billing/card_info') AS X,
XMLTABLE ('$doc/transmission/order/line_items/line_item'  PASSING xmlOrderX.doc AS "doc"
COLUMNS
line_number char(40) PATH 'line_number',
type_code VARCHAR(40)  PATH 'type_code',
product_name VARCHAR(40) PATH 'product_name', 
mincron_item_id VARCHAR(40)  PATH 'mincron_item_id',
external_item_id VARCHAR(40) PATH 'external_item_id', 
pim_id VARCHAR(40)  PATH 'pim_id',
bundle_id VARCHAR(40)  PATH 'bundle_id ', 
quantity VARCHAR(40)  PATH 'quantity', 
line_amount VARCHAR(40)  PATH 'price/amount', 
cost VARCHAR(40)  PATH 'price/cost', 
line_surcharge_amount VARCHAR(40)  PATH 'price/surcharge_amount' ,
line_taxAmount VARCHAR(40)  PATH 'price/tax_info',
taxPercent VARCHAR(40)  PATH 'price/tax_info/percentage',
price_override VARCHAR(40)  PATH 'price/price_override' 
) as Y;