-- Commission Rate Lookup Function for ARPCOMMTX Matrix Table
-- This function demonstrates how to retrieve commission rates based on the matrix criteria

-- Function to get commission rate for given parameters
CREATE OR REPLACE FUNCTION GET_COMMISSION_RATE(
    IN P_GEO_SALES_ZONE INTEGER,
    IN P_COMPANY_NUMBER INTEGER, 
    IN P_DIVISION_CODE CHAR(3),
    IN P_SECTION_CODE CHAR(3),
    IN P_SALES_AMOUNT DECIMAL(15,2),
    IN P_PROFIT_PERCENT DECIMAL(5,2)
)
RETURNS DECIMAL(5,2)
LANGUAGE SQL
READS SQL DATA
BEGIN
    DECLARE V_COMM_RATE DECIMAL(5,2) DEFAULT 0;
    
    SELECT COMM_RATE
    INTO V_COMM_RATE
    FROM ARPCOMMTX 
    WHERE GEO_SALES_ZONE = P_GEO_SALES_ZONE
      AND COMPANY_NUMBER = P_COMPANY_NUMBER
      AND DIVISION_CODE = P_DIVISION_CODE
      AND SECTION_CODE = P_SECTION_CODE
      AND P_SALES_AMOUNT BETWEEN SALES_LOW AND SALES_HIGH
      AND P_PROFIT_PERCENT BETWEEN PROFIT_LOW AND PROFIT_HIGH;
    
    RETURN V_COMM_RATE;
END;

-- Example usage queries
-- 1. Get commission rate for ECM/AMN with $50,000 sales and 12% profit
SELECT GET_COMMISSION_RATE(3, 1, 'ECM', 'AMN', 50000.00, 12.0) as COMMISSION_RATE;

-- 2. Get commission rate for WES/SUP with $200,000 sales and 22.2% profit  
SELECT GET_COMMISSION_RATE(3, 1, 'WES', 'SUP', 200000.00, 22.2) as COMMISSION_RATE;

-- 3. Batch lookup for multiple sales scenarios
WITH SALES_DATA AS (
    SELECT 3 as GEO_ZONE, 1 as COMPANY, 'ECM' as DIV, 'AMN' as SECT, 25000.00 as SALES, 8.5 as PROFIT_PCT
    UNION ALL
    SELECT 3, 1, 'ECM', 'AMN', 75000.00, 12.5
    UNION ALL  
    SELECT 3, 1, 'WES', 'EQP', 150000.00, 11.0
    UNION ALL
    SELECT 3, 1, 'WES', 'SUP', 250000.00, 24.8
    UNION ALL
    SELECT 4, 1, 'ECM', 'AMX', 100000.00, 20.0
)
SELECT SD.*,
       GET_COMMISSION_RATE(SD.GEO_ZONE, SD.COMPANY, SD.DIV, SD.SECT, SD.SALES, SD.PROFIT_PCT) as COMM_RATE,
       ROUND(SD.SALES * GET_COMMISSION_RATE(SD.GEO_ZONE, SD.COMPANY, SD.DIV, SD.SECT, SD.SALES, SD.PROFIT_PCT) / 100, 2) as COMMISSION_AMOUNT
FROM SALES_DATA SD;

-- 4. Alternative lookup without function (direct query approach)
SELECT A.*,
       C.COMM_RATE,
       ROUND(A.SALES_AMOUNT * C.COMM_RATE / 100, 2) as COMMISSION_AMOUNT
FROM (
    -- Sample sales data
    VALUES 
    (3, 1, 'ECM', 'AMN', 25000.00, 8.5),
    (3, 1, 'ECM', 'AMN', 75000.00, 12.5),
    (3, 1, 'WES', 'EQP', 150000.00, 11.0),
    (3, 1, 'WES', 'SUP', 250000.00, 24.8),
    (4, 1, 'ECM', 'AMX', 100000.00, 20.0)
) AS A(GEO_ZONE, COMPANY, DIVISION, SECTION, SALES_AMOUNT, PROFIT_PCT)
LEFT JOIN ARPCOMMTX C ON 
    C.GEO_SALES_ZONE = A.GEO_ZONE
    AND C.COMPANY_NUMBER = A.COMPANY  
    AND C.DIVISION_CODE = A.DIVISION
    AND C.SECTION_CODE = A.SECTION
    AND A.SALES_AMOUNT BETWEEN C.SALES_LOW AND C.SALES_HIGH
    AND A.PROFIT_PCT BETWEEN C.PROFIT_LOW AND C.PROFIT_HIGH;

-- 5. Validation query to check for gaps or overlaps in the matrix
WITH MATRIX_VALIDATION AS (
    SELECT GEO_SALES_ZONE, COMPANY_NUMBER, DIVISION_CODE, SECTION_CODE,
           SALES_LOW, SALES_HIGH, PROFIT_LOW, PROFIT_HIGH,
           LAG(PROFIT_HIGH) OVER (
               PARTITION BY GEO_SALES_ZONE, COMPANY_NUMBER, DIVISION_CODE, SECTION_CODE, SALES_LOW, SALES_HIGH 
               ORDER BY PROFIT_LOW
           ) as PREV_PROFIT_HIGH
    FROM ARPCOMMTX
)
SELECT *,
       CASE 
           WHEN PREV_PROFIT_HIGH IS NOT NULL AND PROFIT_LOW > PREV_PROFIT_HIGH + 0.1 THEN 'GAP_DETECTED'
           WHEN PREV_PROFIT_HIGH IS NOT NULL AND PROFIT_LOW < PREV_PROFIT_HIGH THEN 'OVERLAP_DETECTED'  
           ELSE 'OK'
       END as VALIDATION_STATUS
FROM MATRIX_VALIDATION
WHERE PREV_PROFIT_HIGH IS NOT NULL
ORDER BY GEO_SALES_ZONE, COMPANY_NUMBER, DIVISION_CODE, SECTION_CODE, SALES_LOW, PROFIT_LOW;