-- Query to get complete ARPMCUSX table structure with field names and types
SELECT 
    COLUMN_NAME,
    DATA_TYPE,
    CHARACTER_MAXIMUM_LENGTH,
    NUMERIC_PRECISION,
    NUMERIC_SCALE,
    IS_NULLABLE,
    COLUMN_DEFAULT,
    ORDINAL_POSITION
FROM QSYS2.SYSCOLUMNS
WHERE TABLE_NAME = 'ARPMCUSX'
  AND TABLE_SCHEMA = 'JAMIEDEV'
ORDER BY ORDINAL_POSITION;
