-- Query to see ARPMCUSX table structure and sample data
SELECT * FROM ARPMCUSX FETCH FIRST 1 ROW ONLY;

-- Query to see column definitions
SELECT 
    COLUMN_NAME,
    DATA_TYPE,
    CHARACTER_MAXIMUM_LENGTH,
    IS_NULLABLE,
    COLUMN_DEFAULT
FROM QSYS2.SYSCOLUMNS
WHERE TABLE_NAME = 'ARPMCUSX'
ORDER BY ORDINAL_POSITION;
