-- SQL for checking source member locks on IBM i
-- Updated to use available views and avoid non-existent MEMBER_LOCK_INFO

-- Query 1: Check for object locks on source physical files
SELECT 
    SYSTEM_OBJECT_SCHEMA as LIBRARY,
    SYSTEM_OBJECT_NAME as SOURCE_FILE,
    OBJECT_TYPE,
    LOCK_STATE,
    LOCK_STATUS,
    LOCK_SCOPE,
    LOCK_REQUEST_TYPE,
    JOB_NAME,
    AUTHORIZATION_NAME as USER_NAME,
    LOCK_COUNT,
    LOCK_REQUEST_TIME
FROM QSYS2.OBJECT_LOCK_INFO 
WHERE SYSTEM_OBJECT_NAME LIKE '%SRC'
  AND LOCK_STATE <> 'NONE'
ORDER BY SYSTEM_OBJECT_SCHEMA, SYSTEM_OBJECT_NAME;

-- Query 2: Check for record locks on source files (alternative to member locks)
SELECT 
    SYSTEM_TABLE_SCHEMA as LIBRARY,
    SYSTEM_TABLE_NAME as SOURCE_FILE,
    SYSTEM_TABLE_MEMBER as MEMBER_NAME,
    RELATIVE_RECORD_NUMBER,
    LOCK_STATE,
    LOCK_SCOPE,
    JOB_NAME,
    AUTHORIZATION_NAME as USER_NAME,
    LOCK_REQUEST_TIME
FROM QSYS2.RECORD_LOCK_INFO
WHERE SYSTEM_TABLE_NAME LIKE '%SRC'
  AND LOCK_STATE <> 'NONE'
ORDER BY SYSTEM_TABLE_SCHEMA, SYSTEM_TABLE_NAME, SYSTEM_TABLE_MEMBER;

-- Query 3: Check for locks on specific source file JF003182/QRPGLESRC
SELECT 
    SYSTEM_OBJECT_SCHEMA as LIBRARY,
    SYSTEM_OBJECT_NAME as SOURCE_FILE,
    LOCK_STATE,
    LOCK_STATUS,
    LOCK_SCOPE,
    JOB_NAME,
    AUTHORIZATION_NAME as USER_NAME,
    LOCK_COUNT,
    LOCK_REQUEST_TIME,
    CASE 
        WHEN LOCK_STATE = '*EXCLRD' THEN 'Exclusive Read'
        WHEN LOCK_STATE = '*EXCL' THEN 'Exclusive'
        WHEN LOCK_STATE = '*SHRD' THEN 'Shared Read'
        WHEN LOCK_STATE = '*SHRNUP' THEN 'Shared No Update'
        WHEN LOCK_STATE = '*SHRUPD' THEN 'Shared Update'
        WHEN LOCK_STATE = 'NONE' THEN 'No Lock'
        ELSE LOCK_STATE
    END as LOCK_TYPE_DESC
FROM QSYS2.OBJECT_LOCK_INFO
WHERE SYSTEM_OBJECT_SCHEMA = 'JF003182'
  AND SYSTEM_OBJECT_NAME = 'QRPGLESRC';

-- Query 4: Check for record locks on PERZIP member specifically
SELECT 
    SYSTEM_TABLE_SCHEMA as LIBRARY,
    SYSTEM_TABLE_NAME as SOURCE_FILE,
    SYSTEM_TABLE_MEMBER as MEMBER_NAME,
    RELATIVE_RECORD_NUMBER,
    LOCK_STATE,
    LOCK_SCOPE,
    JOB_NAME,
    AUTHORIZATION_NAME as USER_NAME,
    LOCK_REQUEST_TIME,
    CASE 
        WHEN LOCK_STATE = '*EXCLRD' THEN 'Exclusive Read'
        WHEN LOCK_STATE = '*EXCL' THEN 'Exclusive'
        WHEN LOCK_STATE = '*SHRD' THEN 'Shared Read'
        WHEN LOCK_STATE = '*SHRNUP' THEN 'Shared No Update'
        WHEN LOCK_STATE = '*SHRUPD' THEN 'Shared Update'
        WHEN LOCK_STATE = 'NONE' THEN 'No Lock'
        ELSE LOCK_STATE
    END as LOCK_TYPE_DESC
FROM QSYS2.RECORD_LOCK_INFO
WHERE SYSTEM_TABLE_SCHEMA = 'JF003182'
  AND SYSTEM_TABLE_NAME = 'QRPGLESRC'
  AND SYSTEM_TABLE_MEMBER = 'PERZIP';

-- Query 5: Alternative using QSYS2.OBJECT_STATISTICS for general info
SELECT 
    OBJNAME as OBJECT_NAME,
    OBJLIB as LIBRARY,
    OBJTYPE as OBJECT_TYPE,
    OBJOWNER as OWNER,
    LAST_USED_TIMESTAMP,
    LAST_RESET_TIMESTAMP,
    DAYS_USED_COUNT
FROM QSYS2.OBJECT_STATISTICS 
WHERE OBJLIB = 'JF003182' 
  AND OBJNAME = 'QRPGLESRC'
  AND OBJTYPE = '*FILE';

-- Query 6: Check using SYSLIMITS to see what views are available (diagnostic)
-- This helps identify what lock-related views exist on your system
SELECT 
    TABLE_SCHEMA,
    TABLE_NAME,
    TABLE_TYPE
FROM QSYS2.SYSTABLES 
WHERE TABLE_SCHEMA = 'QSYS2'
  AND TABLE_NAME LIKE '%LOCK%'
ORDER BY TABLE_NAME;

-- Query 7: Alternative approach - Check job information for potential lock holders
-- This shows active jobs that might be holding locks
SELECT 
    JOB_NAME,
    JOB_USER,
    JOB_NUMBER,
    SUBSYSTEM,
    JOB_STATUS,
    AUTHORIZATION_NAME,
    CPU_TIME,
    ELAPSED_TIME
FROM QSYS2.ACTIVE_JOB_INFO
WHERE JOB_STATUS = 'ACTIVE'
  AND AUTHORIZATION_NAME IS NOT NULL
ORDER BY CPU_TIME DESC;

-- Query 8: Check open file information (if available)
-- This may show what jobs have the source file open
SELECT 
    JOB_NAME,
    AUTHORIZATION_NAME,
    SYSTEM_TABLE_SCHEMA as LIBRARY,
    SYSTEM_TABLE_NAME as FILE_NAME,
    SYSTEM_TABLE_MEMBER as MEMBER_NAME,
    OPEN_TYPE,
    OPEN_COUNT
FROM QSYS2.OPEN_FILES
WHERE SYSTEM_TABLE_SCHEMA = 'JF003182'
  AND SYSTEM_TABLE_NAME = 'QRPGLESRC'
ORDER BY JOB_NAME;

-- Query 9: Simple check for any locks on the specific source file
SELECT 
    SYSTEM_OBJECT_SCHEMA as LIBRARY,
    SYSTEM_OBJECT_NAME as SOURCE_FILE,
    LOCK_STATE,
    JOB_NAME,
    AUTHORIZATION_NAME as USER_NAME,
    LOCK_REQUEST_TIME
FROM QSYS2.OBJECT_LOCK_INFO
WHERE SYSTEM_OBJECT_SCHEMA = 'JF003182'
  AND SYSTEM_OBJECT_NAME = 'QRPGLESRC'
  AND LOCK_STATE <> 'NONE';

-- Query 10: Check if QSYS2.FILE_LOCK_INFO exists (alternative table)
/*
SELECT 
    SYSTEM_TABLE_SCHEMA as LIBRARY,
    SYSTEM_TABLE_NAME as SOURCE_FILE,
    LOCK_STATE,
    JOB_NAME,
    AUTHORIZATION_NAME,
    LOCK_REQUEST_TIME
FROM QSYS2.FILE_LOCK_INFO
WHERE SYSTEM_TABLE_SCHEMA = 'JF003182'
  AND SYSTEM_TABLE_NAME = 'QRPGLESRC';
*/